plugins {
    id "com.github.johnrengelman.shadow" version "8.1.1"
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentForge.extendsFrom common
}

repositories {
    maven {
        name = "ModMaven"
        url = "https://modmaven.dev"
        content {
            includeGroup "mezz.jei"
        }
    }
    maven {
        name = "TerraformersMC"
        url = "https://maven.terraformersmc.com/"
        content {
            includeGroup "dev.emi"
        }
    }
}

architectury {
    platformSetupLoomIde()
    forge()
}

loom {
    runs {
        data {
            data()
            name "Data Generation"
            programArgs("--all", "--mod", "hardcorequesting")
            programArgs("--output", file("../common/src/generated/resources").absolutePath)
            programArgs("--existing", file("../common/src/main/resources").absolutePath)
        }
    }
}

dependencies {
    forge "net.minecraftforge:forge:${project.minecraft_version}-${project.forge_version}"

    compileOnly("org.jetbrains:annotations:${project.annotations_version}")
    forgeDependencies(implementation("blue.endless:jankson:${project.jankson_version}"))
    shadowCommon("blue.endless:jankson:${project.jankson_version}")
    modImplementation "dev.architectury:architectury-forge:${project.architectury_version}"

    common(project(path: ":common", configuration: "namedElements")) { transitive false }
    shadowCommon(project(path: ":common", configuration: "transformProductionForge")) {
        transitive = false
    }

    // Loads the item viewer set in dev_item_viewer
    def viewer = project.dev_item_viewer
    if (viewer == "jei") {
        modLocalRuntime("mezz.jei:jei-1.20.1-forge:${project.jei_version}")
    } else if (viewer == "emi") {
        modLocalRuntime("dev.emi:emi-forge:${project.emi_version}")
    } else if (viewer == "rei") {
        modLocalRuntime("me.shedaniel:RoughlyEnoughItems-forge:${project.fabric_roughlyenoughitems}")
    }
}

processResources {
    inputs.property "version", project.version

    filesMatching("META-INF/mods.toml") {
        expand "version": project.version
    }
}

shadowJar {
    relocate "hardcorequesting.common", "hardcorequesting.common.forge"
    relocate "blue.endless.jankson", "hardcorequesting.common.forge.blue.endless.jankson"

    configurations = [project.configurations.shadowCommon]
    archiveClassifier = "dev-shadow"
}

remapJar {
    input.set shadowJar.archiveFile
    dependsOn shadowJar
    archiveClassifier = "forge"
}

jar {
    archiveClassifier = "dev"
}

sourcesJar {
    def commonSources = project(":common").sourcesJar
    dependsOn commonSources
    from commonSources.archiveFile.map { zipTree(it) }
}
